vich_uploader:
    db_driver: orm

    mappings:
        stagiaire_image:
            uri_prefix: /images/stagiaires
            upload_destination: '%kernel.project_dir%/public/images/stagiaires'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
